version: '3.3'
services:
  ELK_master:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: elk_master
    volumes:
      - ./elasticsearch-master.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - masterdb:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
      ELASTIC_PASSWORD: Password2022
      bootstrap.memory_lock: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: "host"
    ports:
      - "9200:9200"
      - "9300:9300"
volumes:
  masterdb:
    driver: local